Sprint №8
AnatolyB0brov/java-kanban pull request #10
Opened 2024-07-17 15:02 UTC by AnatolyB0brov

2024-07-18 18:48 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
>      public boolean updateTask(Task task) {
Почему где-то `boolean`, а где-то `int` возвращается в методах создания?

1. Хочется, чтобы они были единообразными
2. В подобных ситуациях необходимо выбрасывать исключение

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
> +    public TreeSet<Task> getPrioritizedTasks() {
Публичные методы должны быть задекларированы в интерфейсе и как следствие иметь аннотацию `@Override`

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
> +    private <T extends Task> void removeAllFromPrioritizedTasks(Collection<T> taskList) {
Метод называется не совсем корректно, ты удаляешь не все таски, а только переданные

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
> +                if (t.getId().equals(task.getId())) {
Условия в условных операторах можно объединить

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
> +            if (task.getStartTime().isBefore(t.getEndTime()) && t.getStartTime().isBefore(task.getEndTime())) {
Здесь достаточно использовать `return` той конструкции, которая находится в условии

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/task/Epic.java
> +    private LocalDateTime endTime;
А этот параметр нам зачем, если в дальнейшем мы его не используем?

2024-07-18 18:48 UTC, LexLippi commented on src/main/java/task/Task.java
> +/*        if (task.getStartTime() == null && this.getStartTime() == null) {
Закомментированный код не стоит хранить, его всегда можно восстановить с помошью системы контроля версий

2024-07-18 18:48 UTC, LexLippi commented on test/java/manager/FileBackedTaskManagerTest.java
> +    }
Этот метод ничего не тестирует. Зачем он нам нужен в тестовом файле?

2024-07-18 18:48 UTC, LexLippi commented on test/java/manager/InMemoryTaskManagerTest.java
> +        return Managers.getDefault();
Аналогично тому, что уже писал

2024-07-18 18:48 UTC, LexLippi commented on test/java/manager/TaskManagerTest.java
> +    protected abstract TaskManager createTaskManager();
1. Нам для этого не нужен метод, достаточно просто завести поле и инициализировать его по-разному в разных наследниках
2. В абстрактный класс мы хотим вынести тесты, которые имеют единое поведение, вне зависимости от реализации менеджера

2024-07-19 06:41 UTC, AnatolyB0brov commented on test/java/manager/FileBackedTaskManagerTest.java
> +    }
Это мне в Пачке подсказали так сделать

2024-07-19 06:44 UTC, AnatolyB0brov commented on src/main/java/manager/InMemoryTaskManager.java
>      public boolean updateTask(Task task) {
В подобных - это каких?. Я вижу только название метода.

2024-07-19 06:44 UTC, AnatolyB0brov commented on src/main/java/manager/InMemoryTaskManager.java
>      public boolean updateTask(Task task) {
![Скрин](https://github.com/user-attachments/assets/dc902e3f-65dd-418a-ac1e-ae98fafac7dd)

2024-07-19 06:49 UTC, AnatolyB0brov commented on src/main/java/manager/InMemoryTaskManager.java
>      public boolean updateTask(Task task) {
А по первому моменту.
int возвращается в методах создания, а boolean  - в методах обновления.
При создании я возвращаю id задачи, т.к. её по-другому не узнать, а при обновлении смысл возвращать id?.
Пользователю ведь нужно знать, прошло обновление или нет. Зачем возвращать id, который и так известен?

2024-07-19 06:58 UTC, AnatolyB0brov commented on src/main/java/manager/InMemoryTaskManager.java
> +            if (task.getStartTime().isBefore(t.getEndTime()) && t.getStartTime().isBefore(task.getEndTime())) {
Да вроде бы нельзя. Обычно idea сама подсказывает, если можно было бы.
Здесь, если вернуть результат условия, то возврат произойдет после первой же итерации цикла. Смысл тогда от цикла? Ну вернет от false сразу же, а, допустим, во второй итерации, будет true. А мы вернули false, сказав, что пересечений по времени нет, когда они есть. Наша же задача найти хотя бы одно пересечение.

2024-07-19 07:13 UTC, AnatolyB0brov commented on test/java/manager/FileBackedTaskManagerTest.java
> +    }
Так а что здесь не так? Разве в тестовых классах только методы, которые что-то тестируют?
Там же есть еще методы, которые что-то устанавливают(какие-то значения). Конкретно этот метод инициализирует конкретную реализацию TaskManager. Таким образом, метод beforeEach я могу вынести в абстрактный класс. А уже метод createTaskManager подставит конкретную реализацию.

2024-07-19 07:14 UTC, AnatolyB0brov commented on test/java/manager/InMemoryTaskManagerTest.java
> +        return Managers.getDefault();
Тоже самое

2024-07-19 07:16 UTC, AnatolyB0brov commented on test/java/manager/TaskManagerTest.java
> +    protected abstract TaskManager createTaskManager();
Одним полем не обойдешься. Если я хочу вынести реализацию beforeEach в абстрактный класс. В этом методе у меня TaskManager обновляется перед каждым тестом, чтобы действия предыдущего теста никак не влияли на результат следующего.

2024-07-20 07:39 UTC, LexLippi requested changes
Привет!

Ответил на твои комментарии!

Надеюсь после этого стало понятнее, что необходимо доделать!

Желаю удачи!

2024-07-20 07:39 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
> +            if (task.getStartTime().isBefore(t.getEndTime()) && t.getStartTime().isBefore(task.getEndTime())) {
Согласен, недостаточно подробно описал, с использованием Stream API можно было бы сократить это до одной строчки, но при данной реализации нельзя.

Добавление Stream API одна из тем этого спринта, для того чтобы понять, как это сделать пригодятся такие функции, как `.anyMatch`, `.noneMatch`, `.allMatch` и, возможно стандартный `.filter`

2024-07-20 07:39 UTC, LexLippi commented on src/main/java/manager/InMemoryTaskManager.java
>      public boolean updateTask(Task task) {
Согласен, меня смутило скорее другое. Что в исключительной ситуации мы не выбрасываем исключение, и если в методе `update` и возвращаемом булевском значении это можно еще объяснить

То возвращать -1 в методе создания задач, если не удается их создать это какой-то неочевидный `side effect`, от которого легко можно избавиться с помощью исключений (например, проверяемых)

2024-07-20 07:39 UTC, LexLippi commented on test/java/manager/TaskManagerTest.java
> +    protected abstract TaskManager createTaskManager();
Тут согласен, если хотим сделать общий `beforeEach`, то не получится обойтись одним полем.
Помимо этого меня глобально смутило, что ты вынес в `beforeEach` общую инициализацию, но не вынес тесты для общих методов `InMemoryTaskManager` и `FileBackedTaskManager`

2024-07-23 13:56 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-24 10:47 UTC, merged