Sprint №9.
AnatolyB0brov/java-kanban pull request #11
Opened 2024-07-24 10:59 UTC by AnatolyB0brov

2024-07-25 08:02 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/dto/DtoMapper.java
> +public class DtoMapper {
Это класс-помощник или `UtilityClass`. Его стоит оформлять таким образом:

https://www.baeldung.com/java-helper-vs-utility-classes

Два нюанса, которых здесь нет:

1. Приватный конструктор без аргументов
2. Модификатор `final` у самого класса

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/dto/DtoMapper.java
> +        }
Чтобы не инициализировать переменную пустым значением можно использовать тернарный оператор

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/HttpTaskServer.java
> +    }
`main` обычно делают в конце класса, так как это наименее существенный структурный элемент, и часто его в ближайшем будущем придется удалить

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
А почему это поле статическое?
Кажется, что для разных сценариев нам может потребоваться несколько разных серверов в рамках одного запущенного инстанса программы, тогда и метод `createAndStartServer` лучше сделать не статическим

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/adapter/DurationAdapter.java
> +        }
Можно использовать тернарный оператор

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/handler/BaseHttpHandler.java
> +        if (pathParts.length == 2) {
Можно сделать `switch-case` по длине этого поля

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/handler/HistoryHandler.java
> +        }
Лучше везде в таком случае использовать `switch-case`

2024-07-25 08:02 UTC, LexLippi commented on src/main/java/http/handler/PrioritizedHandler.java
> +        if (Objects.requireNonNull(endpoint) == Endpoint.GET) {
Аналогично тому, что писал ранее

2024-07-25 08:15 UTC, AnatolyB0brov commented on src/main/java/dto/DtoMapper.java
> +public class DtoMapper {
Я его забыл удалить, он не нужен мне

2024-07-25 08:17 UTC, AnatolyB0brov commented on src/main/java/http/handler/BaseHttpHandler.java
> +        if (pathParts.length == 2) {
Idea сама предложила преобразовать switch на if, т.к. тут всего один кейс и один дефолт. И я с ней согласен, смысл тут от свича?

2024-07-25 08:18 UTC, AnatolyB0brov commented on src/main/java/http/handler/HistoryHandler.java
> +        }
Почему? Тут тоже будет только один кейс и дефолт

2024-07-25 08:18 UTC, AnatolyB0brov commented on src/main/java/http/handler/PrioritizedHandler.java
> +        if (Objects.requireNonNull(endpoint) == Endpoint.GET) {
Аналогично и тут

2024-07-25 08:19 UTC, AnatolyB0brov commented on src/main/java/http/handler/PrioritizedHandler.java
> +        if (Objects.requireNonNull(endpoint) == Endpoint.GET) {
Эти замечания по свичу кажутся странными

2024-07-25 09:43 UTC, AnatolyB0brov commented
Привет. Спасибо за ревью!

2024-07-25 09:51 UTC, AnatolyB0brov commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
Ты пишешь сделать метод, который вызывается в статическом методе main, не статическим. Это как?

2024-07-25 09:55 UTC, AnatolyB0brov commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
А поле httpServer используется в статическом методе и тоже должно быть статическим

2024-07-26 08:25 UTC, LexLippi commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
Ну в статическом методе `main` можно просто создать объект типа `HttpTaskServer` и работать с его полями и методами.

Примерно, так:

```java
public class Main {
    public int a;
    
	public static void main(String[] args) {
	    var main = new Main();
	    main.a = 2;
	    var otherMain = new Main();
	    otherMain.a = 1;
		System.out.println(main.a == otherMain.a);
	}
}
```

2024-07-26 08:28 UTC, LexLippi commented
Привет!

По поводу статического и не статического метода, отписал подробнее, что я имею в виду.

По поводу `switch` вопрос дискусионный действительно, но по опыту, скажу что если мы делаем `switch` на одно значение и дефолт, то рано или поздно это в большинстве случае выродится в обычный `switch` по мере жизни программы.

2024-07-26 08:32 UTC, LexLippi commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
Это один вариант, второй вариант, если мы используем метод `createAndStartServer` в качестве статического конструктора (такое тоже допустимо), то он должен возвращать инициализированный и запущенный `HttpTaskServer`, как мы уже делали с `FileBackedTaskManager`.

Опять же по опыту скажу, что статическими в основном делают вещи утилитарные, типа маппера объектов. Все остальное же (по умолчанию) делают не статическим, чтобы получить дополнительную гибкость используемых конструкций и возможность переиспользования.

2024-07-26 08:33 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Ответил на твои комментарии, в целом, эти доработки можно не делать, если нет большого желания или внутреннего согласия со мной.

Отправь проект в этом же виде еще раз и я приму его!

2024-07-26 16:40 UTC, AnatolyB0brov commented on src/main/java/http/HttpTaskServer.java
> +    private static HttpServer httpServer;
Сделал не статическим

2024-07-26 16:47 UTC, AnatolyB0brov commented
Привет.
Спасибо, всё разъяснил.
Статик убрал.
Свич не добавлял - решил последовать совету Роберта Мартина и не усложнять код раньше, чем потребуется, ведь есть вероятность, что усложнение не понадобится вообще.
Если добавится еще одно условие, то - да, сделаю свич.  А до тех пор будет if. Тем более, что дальше по программе вижу Spring, а значит, что рано или поздно мы напишем спринговые контроллеры, которые полностью заменят реализацию эндпоинтов. Скорее всего, до замены на свич не дойдет.

2024-07-27 10:20 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-07-27 18:42 UTC, merged