Sprint 6 solution
AnatolyB0brov/java-kanban pull request #8
Opened 2024-07-08 07:57 UTC by AnatolyB0brov

2024-07-09 07:44 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/InMemoryHistoryManager.java
> +        nodeHashMap.remove(id);
Метод `remove` у `HashMap` возвращает удаленное значение, так что можно не обращаться дважды к нашему словарю, а сделать `remove` единственный раз, когда передаем аргумент в метод `removeNode`

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/InMemoryHistoryManager.java
> +import org.apache.commons.lang3.SerializationUtils;
Можно оставить и так, но дефолтная реализация метода `clone()` довольно медленная, поэтому на самом деле достаточно просто реализовать java copy constructor.

https://www.baeldung.com/java-copy-constructor

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/InMemoryHistoryManager.java
> +        if (oldTail == null)
В соответствии с Google Java Code Style советую всегда использовать фигурные скобки, даже когда они опциональны:

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/Node.java
> +public class Node<T> {
Хотелось бы, чтобы данный класс был `final` и его нельзя было бы наследовать, чтобы не изменить нашу функциональность

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/Node.java
> +    public Node<T> prev;
Если это публичный класс, то мы хотим, чтобы его поля были `protected` или даже `private` для соблюдения инкапсуляции

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/history/Node.java
> +public class Node<T> {
В нашем случае достаточно, чтобы `T` был наследником класса `Task`, но можно оставить и более общий вариант

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/task/Epic.java
> +            }
Можно использовать тернарный оператор

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/task/Task.java
> +            return true;
Про опциональные скобки уже писал

2024-07-09 07:44 UTC, LexLippi commented on src/main/java/task/Task.java
> +            return false;
Два условных оператора можно объединить в один

2024-07-09 09:12 UTC, AnatolyB0brov commented on src/main/java/history/InMemoryHistoryManager.java
> +import org.apache.commons.lang3.SerializationUtils;
Оставлю так, т.к. clone делает deepCopy, что даёт гарантии полного копирования, даже когда объект станет сложнее. Но у меня уже не будет болеть по этому поводу голова.

2024-07-09 09:13 UTC, AnatolyB0brov commented on src/main/java/history/Node.java
> +public class Node<T> {
Оставил более общий вариант

2024-07-10 08:32 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-10 12:58 UTC, merged