Sprint №7
AnatolyB0brov/java-kanban pull request #9
Opened 2024-07-11 12:55 UTC by AnatolyB0brov

2024-07-12 08:54 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-12 08:54 UTC, LexLippi commented on src/main/java/manager/FileBackedDto.java
> +        return tasks;
Хотим возвращать копию объекта в методе `get` иначе не соблюдается инкапсуляция
Аналогично для всех остальных  `get`-методов

2024-07-12 08:54 UTC, LexLippi commented on src/main/java/manager/FileBackedTaskManager.java
> +    }
1. А почему здесь нет сохранения после вызова родительского метода
2. Нет смысла переопределять метод, если мы ничего в нем не меняем

2024-07-12 08:54 UTC, LexLippi commented on src/main/java/manager/FileBackedTaskManager.java
> +            FileBackedDto fileBackedDto = (FileBackedDto) objectInputStream.readObject();
Здесь стоит добавить проверку, что считанный объект действительно `FileBackedDto`.

Например, так:

```java
Object obj = objectInputStream.readObject();
if (obj instanceof FileBackedDto) {
    FileBackedDto fileBackedDto = (FileBackedDto) obj;
}
```

2024-07-12 08:54 UTC, LexLippi commented on src/main/java/manager/FileBackedTaskManager.java
> +            return fileBackedTaskManager;
Восстановленный менеджер некорректен, так как не хватает восстановления двух параметров:

1. Истории просмотров
2. Генератора идентификаторов

2024-07-12 08:54 UTC, LexLippi commented on src/main/java/manager/FileBackedTaskManager.java
> +            objectOutputStream.writeObject(fileBackedDto);
Не сохраняем историю просмотров

2024-07-12 11:15 UTC, AnatolyB0brov commented on src/main/java/manager/FileBackedDto.java
> +        return tasks;
Так это же ДТОшка. Я просто достаю из нее объект и забываю про нее, зачем здесь копия?

2024-07-12 12:56 UTC, AnatolyB0brov commented on src/main/java/manager/FileBackedDto.java
> +        return tasks;
Неужели для pojo классов это тоже нужно делать? 
Аннотация @Getter у lombok ведь не делает копию коллекций, а эту аннотацию используют в pojo.

2024-07-13 11:59 UTC, LexLippi commented on src/main/java/manager/FileBackedDto.java
> +        return tasks;
На самом деле pojo-классы бывают разные с точки зрения способа хранения. Какие-то хранятся в SQL или NoSQL СУБД для таких этого можно не делать, а те же, которые мы храним в оперативной памяти во время работы приложения стоит переопределять и оборачивать в копию, поскольку это менее частотный случай, то в lombok реализован более частотный, что логично)

В твоем случае, если dto используется только для сериализации можно не делать копии, если бы мы прямо хранили поле `FileBackedDto` внутри менеджера, то пришлось бы наворачивать копии, да)

2024-07-13 11:59 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-14 14:48 UTC, merged